// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJkyZZKTfpOwqLI34_pRaFWrsoeFXwy9M',
    appId: '1:96703577471:web:86f5710a81a138522b6e4a',
    messagingSenderId: '96703577471',
    projectId: 'todo-list-auditoria',
    authDomain: 'todo-list-auditoria.firebaseapp.com',
    storageBucket: 'todo-list-auditoria.firebasestorage.app',
    measurementId: 'G-0ETRY6SNED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dFLE4arT-Z1pCOZpfd5nuFLJqcai818',
    appId: '1:96703577471:android:75d29aa61c8642ce2b6e4a',
    messagingSenderId: '96703577471',
    projectId: 'todo-list-auditoria',
    storageBucket: 'todo-list-auditoria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_hzWCVBOTf4RdGf0wEeeDOFC9yQoSnI0',
    appId: '1:96703577471:ios:75495966a21f0d202b6e4a',
    messagingSenderId: '96703577471',
    projectId: 'todo-list-auditoria',
    storageBucket: 'todo-list-auditoria.firebasestorage.app',
    iosBundleId: 'com.example.todoListAuditoria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_hzWCVBOTf4RdGf0wEeeDOFC9yQoSnI0',
    appId: '1:96703577471:ios:75495966a21f0d202b6e4a',
    messagingSenderId: '96703577471',
    projectId: 'todo-list-auditoria',
    storageBucket: 'todo-list-auditoria.firebasestorage.app',
    iosBundleId: 'com.example.todoListAuditoria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJkyZZKTfpOwqLI34_pRaFWrsoeFXwy9M',
    appId: '1:96703577471:web:19d5202bc9a702c42b6e4a',
    messagingSenderId: '96703577471',
    projectId: 'todo-list-auditoria',
    authDomain: 'todo-list-auditoria.firebaseapp.com',
    storageBucket: 'todo-list-auditoria.firebasestorage.app',
    measurementId: 'G-RPP4Q8C0D9',
  );
}
